excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ellenjasmin.github.io
title: E.
email: 
author: ellenjasmin
description: My awesome new site
paginate: 3
google_analytics: 